# Generated by Django 5.2.7 on 2025-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_options_certificate_issued_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='download_url',
            field=models.CharField(blank=True, help_text='Cached PDF path or URL for download.', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='meta',
            field=models.JSONField(blank=True, help_text='Additional data (dict) for customization.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', max_length=20),
        ),
    ]
