# Generated by Django 5.2.7 on 2025-11-23 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_download_url_certificate_meta_and_more'),
        ('courses', '0005_course_approved_at_course_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['serial'], name='certificate_serial_0d343b_idx'),
        ),
    ]
