# Generated by Django 5.2.7 on 2025-10-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttransaction_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_tx_id',
            field=models.CharField(max_length=100, verbose_name='Transaction ID'),
        ),
    ]
