# Generated by Django 5.2.8 on 2025-11-19 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_approved_at_course_approved_by_and_more'),
        ('payments', '0005_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_tx_id',
            field=models.CharField(max_length=255, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider'], name='payments_pa_provide_502c98_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_tx_id'], name='payments_pa_provide_852859_idx'),
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
