# Generated by Django 5.2.7 on 2025-10-31 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_remove_lesson_created_at_remove_lesson_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_course', 'Created a Course'), ('updated_course', 'Updated a Course'), ('deleted_course', 'Deleted a Course'), ('added_section', 'Added a Section'), ('edited_section', 'Edited a Section'), ('deleted_section', 'Deleted a Section'), ('added_lesson', 'Added a Lesson'), ('edited_lesson', 'Edited a Lesson'), ('deleted_lesson', 'Deleted a Lesson')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Activity',
                'verbose_name_plural': 'Instructor Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('expertise_area', models.CharField(blank=True, max_length=255)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated languages taught', max_length=255)),
                ('cv_resume', models.FileField(blank=True, null=True, upload_to='instructors/cv/')),
                ('id_verification', models.FileField(blank=True, null=True, upload_to='instructors/id_docs/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='instructors/signatures/')),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructorprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
