# Generated by Django 5.2.8 on 2025-11-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
